#
#  Fastfile
#  ocean-watch-ios
#
#  Created by Illia Kucheriavyi on 27/05/2020.
#  Copyright © 2020 MongoDB. All rights reserved.
#

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Base build check" # this action skips all signing and exporting, only do the base build check (compillability)
  lane :build do
    cocoapods(clean_install: true)
    sh 'cp ../o-fish-ios/LocalConstants.swift.tmpl ../o-fish-ios/LocalConstants.swift'
    gym(clean: true,
        skip_archive: true,
        skip_package_ipa: true,
        skip_codesigning: true)
  end
end
